BoomBackBundle_login:
    pattern:  /login
    defaults: { _controller: BoomBackBundle:Auth:login }

BoomBackBundle_logout:
    pattern:  /logout
    defaults: { _controller: BoomBackBundle:Auth:login }


BoomBackBundle_login_check:
    pattern:   /login_check

BoomBackBundle_homepage:
    pattern:  /
    defaults: { _controller: BoomBackBundle:Default:dashboard }

