BoomBackBundle_login:
    pattern:  /login
    defaults: { _controller: BoomBackBundle:Auth:login }


BoomBackBundle_homepage:
    pattern:  /
    defaults: { _controller: BoomBackBundle:Default:dashboard }

