#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#   prefix: /resetting

#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

BoomBackBundle_login:
    pattern:  /login
    defaults: { _controller: BoomBackBundle:Security:login }

BoomBackBundle_logout:
    pattern:  /logout
    defaults: { _controller: BoomBackBundle:Auth:login }

BoomBackBundle_login_check:
    pattern:   /login_check

BoomBackBundle_homepage:
    pattern:  /
    defaults: { _controller: BoomBackBundle:Default:dashboard }

BoomBackBundle_boom:
    resource: "@BoomBackBundle/Resources/config/routing/boom.yml"
    prefix: /boom