#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#   prefix: /resetting

#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

BoomBackBundle_login:
    pattern:  /login
    defaults: { _controller: BoomBackBundle:Security:login }

BoomBackBundle_logout:
    pattern:  /logout
    defaults: { _controller: BoomBackBundle:Auth:login }

BoomBackBundle_login_check:
    pattern:   /login_check

BoomBackBundle_dashboard:
    pattern:  /
    defaults: { _controller: BoomBackBundle:Default:dashboard }

BoomBackBundle_default_clearcache:
    pattern:  /clear_cache
    defaults: { _controller: BoomBackBundle:Default:clearCache}

BoomBackBundle_list:
    resource: "@BoomBackBundle/Resources/config/routing/list.yml"
    prefix: /list

BoomBackBundle_boom:
    resource: "@BoomBackBundle/Resources/config/routing/boom.yml"
    prefix: /boom

BoomBackBundle_category:
    resource: "@BoomBackBundle/Resources/config/routing/category.yml"
    prefix: /category

BoomBackBundle_user:
    resource: "@BoomBackBundle/Resources/config/routing/user.yml"
    prefix: /user

BoomBackBundle_image:
    resource: "@BoomBackBundle/Resources/config/routing/image.yml"
    prefix: /image

BoomBackBundle_widget:
    resource: "@BoomBackBundle/Resources/config/routing/widget.yml"
    prefix: /widget

BoomBackBundle_gallery:
    resource: "@BoomBackBundle/Resources/config/routing/gallery.yml"
    prefix: /gallery

BoomBackBundle_tag:
    resource: "@BoomBackBundle/Resources/config/routing/tag.yml"
    prefix: /tag