parameters:
    boom_back.image_type.class: Boom\Bundle\BackBundle\Form\Type\ImageType

services:
    form.type.image:
        class: %boom_back.image_type.class%
        tags:
            - { name: form.type, alias: image }