parameters:
    #boom_back.image_type.class: Boom\Bundle\BackBundle\Form\Type\WidgetBlockType
    boom_back.widget_block_type.class: Boom\Bundle\BackBundle\Form\Type\WidgetBlockType
    boom_back.user_provider.admin.class: Boom\Bundle\BackBundle\Security\AdminProvider

services:
    form.type.widget_block_type:
        class: %boom_back.widget_block_type.class%
        arguments:
          - "%boom_widget_blocks%"
        tags:
            - { name: form.type, alias: widget_block }
    boom_back.user_provider.admin:
        class: %boom_back.user_provider.admin.class%
        arguments:
          userManager:  "@fos_user.user_manager"
          #validator:    "@validator"
          #container:    "@service_container"