parameters:
    #boom_back.image_type.class: Boom\Bundle\BackBundle\Form\Type\WidgetBlockType
    boom_back.widget_block_type.class: Boom\Bundle\BackBundle\Form\Type\WidgetBlockType
    boom_back.user_provider.admin.class: Boom\Bundle\BackBundle\Security\AdminProvider
    boom_back.boom_bundle_backbundle_listelementtype.type.class: Boom\Bundle\BackBundle\Form\ListElementType
    boom_back.ajax_image.type.class:  Boom\Bundle\LibraryBundle\Form\BoomType

services:
    form.type.widget_block_type:
        class: %boom_back.widget_block_type.class%
        arguments:
          - "%boom_widget_blocks%"
        tags:
            - { name: form.type, alias: widget_block }
    boom_back.user_provider.admin:
        class: %boom_back.user_provider.admin.class%
        arguments:
          userManager:  "@fos_user.user_manager"
          #validator:    "@validator"
    boom_back.boom_bundle_backbundle_listelementtype.type:
        class: %boom_back.boom_bundle_backbundle_listelementtype.type.class%
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: boom_bundle_backbundle_listelementtype }
    boom_back.boom_back_type.type:
        class: %boom_back.ajax_image.type.class%
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: boom_back }