parameters:
#    boom_user.example.class: Boom\Bundle\UserBundle\Example

services:
#    boom_user.example:
#        class: %boom_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
