parameters:
#    boom_back.example.class: Boom\Bundle\BackBundle\Example

services:
#    boom_back.example:
#        class: %boom_back.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
