BoomFrontBundle_Boom_reorder:
    pattern:  /reordena/{slug}.{_format}
    defaults: { _controller: "BoomFrontBundle:Boom:reorder", _format: "json" }
    requirements: { _method: post }

BoomFrontBundle_boom_image:
    pattern:  /imagen.json
    defaults: { _controller: "BoomFrontBundle:Boom:ajaxImage" }
    requirements: { _method: post }

BoomFrontBundle_boom_reply:
    pattern:  /responde/{slug}
    defaults: { _controller: "BoomFrontBundle:Boom:reply" }

BoomFrontBundle_boom_new:
    pattern:  /nuevo
    defaults: { _controller: "BoomFrontBundle:Boom:new" }
    requirements: { _method: get }

BoomFrontBundle_boom_create:
    pattern:  /nuevo
    defaults: { _controller: "BoomFrontBundle:Boom:create" }
    requirements: { _method: post }

BoomFrontBundle_boom_edit:
    pattern:  /{slug}/editar
    defaults: { _controller: "BoomFrontBundle:Boom:edit" }

BoomFrontBundle_boom_update:
    pattern:  /{slug}/actualizar
    defaults: { _controller: "BoomFrontBundle:Boom:update" }
    requirements: { _method: post }

BoomFrontBundle_boom_delete:
    pattern:  /{slug}/borrar
    defaults: { _controller: "BoomFrontBundle:Boom:delete" }
    requirements: { _method: post }
