#BoomFrontBundle_boom_show:
#    pattern:  /{slug}
#    defaults: { _controller: "BoomFrontBundle:Boom:show" }
#    requirements:
#        slug: ".+"

BoomFrontBundle_boom_index:
    pattern:  /
    defaults: { _controller: "BoomFrontBundle:Boom:index" }

BoomFrontBundle_boom_new:
    pattern:  /new
    defaults: { _controller: "BoomFrontBundle:Boom:new" }

BoomFrontBundle_boom_create:
    pattern:  /create
    defaults: { _controller: "BoomFrontBundle:Boom:create" }
    requirements: { _method: post }

BoomFrontBundle_boom_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BoomFrontBundle:Boom:edit" }

BoomFrontBundle_boom_update:
    pattern:  /{id}/update
    defaults: { _controller: "BoomFrontBundle:Boom:update" }
    requirements: { _method: post }

BoomFrontBundle_boom_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BoomFrontBundle:Boom:delete" }
    requirements: { _method: post }
