BoomFrontBundle_boom_sitemap:
    pattern:  /sitemap.{_format}
    defaults: { _controller: "BoomFrontBundle:Default:sitemap", _format: "xml" }
    requirements:
        _format: "xml"
        _method:  GET

BoomFrontBundle_boom_twit_count:
    pattern:  /tc/{category_slug}/{slug}
    defaults: { _controller: "BoomFrontBundle:Default:twitCount", _format: "json" }
    requirements:
        _method:  GET

BoomFrontBundle_category_show:
    pattern:  /{slug}
    defaults: { _controller: "BoomFrontBundle:Default:category" }
    requirements:
        _method:  GET
        slug: ^[a-z0-9-]+$

BoomFrontBundle_boom_show:
    pattern:  /{category_slug}/{slug}/{username}
    defaults: { _controller: "BoomFrontBundle:Default:boom", username: null }
    requirements:
        _method:  GET
        category_slug: ^[a-z0-9-]+$
        slug: ^[a-z0-9-]+$
        username: ^[A-Za-z0-9_\-\.]+$
    options:
        expose: true