BoomFrontBundle_list_category_recommended:
    pattern:  /recomendados/{category_slug}/{page}
    defaults: { _controller: "BoomFrontBundle:List:recommended",page: 1 }
    requirements:
      page: \d+

BoomFrontBundle_list_recommended:
    pattern:  /recomendados/{page}
    defaults: { _controller: "BoomFrontBundle:List:recommended",page: 1 }
    requirements:
      page: \d+

BoomFrontBundle_list_category_latest:
    pattern:  /ultimos/{category_slug}/{page}
    defaults: { _controller: "BoomFrontBundle:List:latest",page: 1 }
    requirements:
      page: \d+

BoomFrontBundle_list_latest:
    pattern:  /ultimos/{page}
    defaults: { _controller: "BoomFrontBundle:List:latest",page: 1 }
    requirements:
      page: \d+

BoomFrontBundle_list_category_users:
    pattern:  /usuarios/{category_slug}/{page}
    defaults: { _controller: "BoomFrontBundle:List:user",page: 1 }
    requirements:
      page: \d+

BoomFrontBundle_list_users:
    pattern:  /usuarios/{page}
    defaults: { _controller: "BoomFrontBundle:List:user",page: 1 }
    requirements:
      page: \d+

BoomFrontBundle_list_category_collaborator:
    pattern:  /colaborador/{category_slug}/{page}
    defaults: { _controller: "BoomFrontBundle:List:collaborator",page: 1 }
    requirements:
      page: \d+

BoomFrontBundle_list_collaborator:
    pattern:  /colaborador/{page}
    defaults: { _controller: "BoomFrontBundle:List:collaborator",page: 1 }
    requirements:
      page: \d+

BoomFrontBundle_list_category_top:
    pattern:  /top/{category_slug}/{page}
    defaults: { _controller: "BoomFrontBundle:List:top",page: 1 }
    requirements:
      page: \d+

BoomFrontBundle_list_top:
    pattern:  /top/{page}
    defaults: { _controller: "BoomFrontBundle:List:top",page: 1 }
    requirements:
      page: \d+