BoomFrontBundle_profile_index:
    pattern:  /
    defaults: { _controller: "BoomFrontBundle:Profile:index" }

BoomFrontBundle_profile_edit:
    pattern:  /perfil
    defaults: { _controller: "BoomFrontBundle:Profile:edit" }

BoomFrontBundle_profile_recent:
    pattern:  /reciente/{page}
    defaults: { _controller: "BoomFrontBundle:Profile:recent", page: 1  }
    requirements:
      page: \d+

BoomFrontBundle_profile_booms:
    pattern:  /mis_booms/{page}
    defaults: { _controller: "BoomFrontBundle:Profile:booms", page: 1  }
    requirements:
      page: \d+

BoomFrontBundle_profile_recommend:
    pattern:  /recomendados/{page}
    defaults: { _controller: "BoomFrontBundle:Profile:recommended", page: 1  }
    requirements:
      page: \d+

BoomFrontBundle_profile_followings:
    pattern:  /siguiendo/{page}
    defaults: { _controller: "BoomFrontBundle:Profile:followings", page: 1 }
    requirements:
      page: \d+

BoomFrontBundle_profile_followers:
    pattern:  /seguidores/{page}
    defaults: { _controller: "BoomFrontBundle:Profile:followers", page: 1 }
    requirements:
      page: \d+
