BoomFrontBundle_login_fb:
    pattern:  /login_fb
    defaults: { _controller: BoomFrontBundle:Profile:fbLogin }
    requirements:
        _method:  GET

BoomFrontBundle_login_check_fb:
    pattern:   /login_check_fb

BoomFrontBundle_logout:
    pattern:  /logout
    requirements:
        _method:  GET