BoomFrontBundle_user_mail:
    pattern:  /mail
    defaults: { _controller: "BoomFrontBundle:User:mail", _format: "html" }

BoomFrontBundle_user_list:
    pattern:  /
    defaults: { _controller: "BoomFrontBundle:User:list" }

BoomFrontBundle_user_collaborators:
    pattern:  /colaboradores/{page}
    defaults: { _controller: "BoomFrontBundle:User:collaborators", page: 1 }
    requirements:
      page: \d+

BoomFrontBundle_user_profile:
    pattern:  /{username}/{listname}/{page}
    defaults:
        _controller: "BoomFrontBundle:User:profile"
        page: 1
        listname: creados
    requirements:
      username: ^[A-Za-z0-9_\-\.]+$
      listname: creados|modificados
      page: \d+