BoomFrontBundle_user_mySite:
    pattern:  /
    defaults: { _controller: "BoomFrontBundle:User:list" }

BoomFrontBundle_user_profile:
    pattern:  /colaboradores
    defaults: { _controller: "BoomFrontBundle:User:collaborators" }

BoomFrontBundle_user_recent:
    pattern:  /{username}
    defaults: { _controller: "BoomFrontBundle:Boom:profile" }