boom:
    pattern:  /
    defaults: { _controller: "BoomFrontBundle:Boom:index" }

boom_show:
    pattern:  /boom/{slug}
    defaults: { _controller: "BoomFrontBundle:Boom:show" }

boom_new:
    pattern:  /new
    defaults: { _controller: "BoomFrontBundle:Boom:new" }

boom_create:
    pattern:  /create
    defaults: { _controller: "BoomFrontBundle:Boom:create" }
    requirements: { _method: post }

boom_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BoomFrontBundle:Boom:edit" }

boom_update:
    pattern:  /{id}/update
    defaults: { _controller: "BoomFrontBundle:Boom:update" }
    requirements: { _method: post }

boom_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BoomFrontBundle:Boom:delete" }
    requirements: { _method: post }
