imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: doctrine_extensions.yml }
framework:
    esi:             { enabled: false }
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['php','twig'] }
    #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trusted_proxies: ~
    trust_proxy_headers: false # Should Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

fos_user:
    db_driver: orm
    firewall_name: boom_area
    user_class: Boom\Bundle\LibraryBundle\Entity\User
    template:
        engine: php
    group:
        group_class: Boom\Bundle\LibraryBundle\Entity\Group
    from_email:
        address:        admin@7boom.mx
        sender_name:    7Boom Admin
    registration:
        confirmation:
            enabled:    true
fos_facebook:
      file:   %kernel.root_dir%/../vendor/facebook/php-sdk/src/base_facebook.php
      alias:  facebook
      app_id: %facebook_app_id%
      secret: %facebook_app_secret%
      cookie: true
      culture: es_LA
      class:
        helper: Boom\Bundle\FrontBundle\Templating\Helper\FacebookHelper
      permissions:
        - email
        - user_birthday
        - user_location
        - user_education_history
        - user_hometown
        - user_interests
#fos_twitter:
#      file: %kernel.root_dir%/../vendor/kertz/twitteroauth/twitteroauth/twitteroauth.php
#      consumer_key: xxxxxx
#      consumer_secret: xxxxxx
#      callback_url: http://www.example.com/login_check_tw

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles: [BoomBackBundle,BoomFrontBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
      default_connection: default
      connections:
          default:
            driver:   %database_driver%
            host:     %database_host%
            port:     %database_port%
            dbname:   %database_name%
            user:     %database_user%
            password: %database_password%
            charset:  UTF8
      #types:
          #datetime: Boom\Bundle\LibraryBundle\Doctrine\Extensions\DBAL\Types\UTCDateTimeType
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        metadata_cache_driver: array
        query_cache_driver: array
        result_cache_driver: array
        # only these lines are added additionally
        mappings:
          loggable:
              type: annotation
              alias: Gedmo
              prefix: Gedmo\Loggable\Entity
              dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
          tree:
              type: annotation
              alias: Gedmo
              prefix: Gedmo\Tree\Entity
              dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"

fm_bbcode:
    config:
      filters:
        - { classname: boom_video,    class: \Boom\Bundle\FrontBundle\Decoda\Filter\BoomVideoFilter }
        - { classname: boom_gallery,  class: "@boom_front.gallery.decoda.filter" }
        - { classname: boom_url,      class: \Boom\Bundle\FrontBundle\Decoda\Filter\BoomUrlFilter }
      templates:
        - path: %kernel.root_dir%/Resources/Decoda/templates/
    filter_sets:
        default:
          locale: es
          xhtml: true
          filters: [ default, quote, boom_url, image, boom_video, boom_gallery, list, li, olist, p]

# Swiftmailer Configuration
swiftmailer:
    transport: gmail
    host:      %mailer_host%
    username:  'no-reply@7boom.mx'
    password:  '7boom2012-noreply'
    spool:     { type: memory }

boom_library:
    boom_image_sizes:
      - { width: 680, height: 382 , thumbnail: false }
      - { width: 590, height: 380 , thumbnail: false }
      - { width: 133, height: 75  }
      - { width: 116, height: 116 }
      - { width: 158, height: 90  }
      - { width: 72 , height: 72  }
      - { width: 78 , height: 53  }

services:
    cache.apc:
        class: Doctrine\Common\Cache\ApcCache
    cache.array:
        class: Doctrine\Common\Cache\ArrayCache

