# Internal routing configuration to handle ESI
_internal:
    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
    prefix:   /_internal

BoomFrontBundle:
    resource: "@BoomFrontBundle/Resources/config/routing.yml"
    prefix:   /

BoomUserBundle:
    resource: "@BoomUserBundle/Resources/config/routing.yml"
    prefix:   /

BoombackBundle:
    resource: "@BoomBackBundle/Resources/config/routing.yml"
    prefix:   /admin/