# Internal routing configuration to handle ESI
_internal:
    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
    prefix:   /_internal

BoombackBundle:
    resource: "@BoomBackBundle/Resources/config/routing.yml"
    prefix:   /admin/

BoomUserBundle:
    resource: "@BoomUserBundle/Resources/config/routing.yml"
    prefix:   /

BoomFrontBundle:
    resource: "@BoomFrontBundle/Resources/config/routing.yml"
    prefix:   /
