jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_TWITTER:     [IS_AUTHENTICATED_REMEMBERED, ROLE_USER, ROLE_SOCIAL]
        ROLE_FACEBOOK:    [IS_AUTHENTICATED_REMEMBERED, ROLE_USER, ROLE_SOCIAL]
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_facebook_provider:
            id: boom_library.facebook.user
        #fos_twitter_provider:
        #    id: boom_library.twitter.user
        fos_userbundle_provider:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    admin: { password: adminpass, roles: [ 'ROLE_SUPER_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin_login:
            pattern:  ^/admin/login$
            anonymous: ~
        boom_login:
            pattern:  ^/login$
            anonymous: ~
        admin_area:
            pattern:    ^/admin
            provider: in_memory
            logout:
                path: /admin/logout
                target: /admin/login
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
                default_target_path: /admin
        boom_area:
            pattern:    ^/
            remember_me:
              key:      "%secret%"
              lifetime: 3600
              path:     /
              domain: ~
            #form_login:
            #    check_path: /boomer/login_check
            #    login_path: /login
            #    default_target_path: /boomer
            fos_facebook:
                app_url: "http://apps.facebook.com/echo_mx/"
                server_url: "http://sb.here/"
                check_path: /login_check_fb
                login_path: /login_fb
                default_target_path: /
                provider: fos_facebook_provider
            anonymous: true
            logout:
                path: /logout
                target: /
                handlers: ["fos_facebook.logout_handler"]
    access_control:
        - path: ^/_internal/secure
          roles: IS_AUTHENTICATED_ANONYMOUSLY
          ip: 127.0.0.1
        - path: ^/admin/login
          roles: IS_AUTHENTICATED_ANONYMOUSLY
        - path: ^/login
          roles: IS_AUTHENTICATED_ANONYMOUSLY
        - path: ^/admin
          roles: ROLE_SUPER_ADMIN
        - path: ^/boomer
          roles: IS_AUTHENTICATED_FULLY
        - path: ^/
          roles: [IS_AUTHENTICATED_ANONYMOUSLY]