jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin_login:
            pattern:  ^/admin/login$
            security: false
        boom_login:
            pattern:  ^/login$
            security: false          
        admin_area:
            pattern:    ^/admin/
            form_login: ~
            logout: ~            
            #    check_path: /admin/login_check
            #    login_path: /admin/login
            #logout:
            #    path:   /admin/logout
            #    target: /admin/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
        boom_area:
            pattern:    ^/
            form_login: ~
            logout: ~            
            form_login:
                check_path: /boomer/login_check
                login_path: /login
            anonymous: ~


    access_control:
        - path: ^/admin/login
          roles: IS_AUTHENTICATED_ANONYMOUSLY
        - path: ^/login
          roles: IS_AUTHENTICATED_ANONYMOUSLY
        - path: ^/
          roles: IS_AUTHENTICATED_ANONYMOUSLY
        - path: ^/_internal/secure
          roles: IS_AUTHENTICATED_ANONYMOUSLY
          ip: 127.0.0.1
