jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_TWITTER:     [IS_AUTHENTICATED_REMEMBERED, ROLE_USER, ROLE_SOCIAL]
        ROLE_FACEBOOK:    [IS_AUTHENTICATED_REMEMBERED, ROLE_USER, ROLE_SOCIAL]
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: adminpass, roles: [ 'ROLE_SUPER_ADMIN','ROLE_ADMIN' ] }
        boom_fos_facebook_provider:
            id: boom_front.facebook.user
        boom_fos_admin_provider:
            id: boom_back.user_provider.admin
        #fos_twitter_provider:
        #    id: boom_library.twitter.user
        fos_userbundle_provider:
            id: fos_user.user_provider.username
        admin_chain_provider:
            chain:
                 providers:
                  - in_memory
                  - boom_fos_admin_provider
        boom_chain_provider:
            chain:
                 providers:
                  - boom_fos_facebook_provider
                  - fos_userbundle_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin_login:
            pattern:  ^/admin/login$
            anonymous: ~
        admin_area:
            pattern:    ^/admin
            provider: admin_chain_provider
            logout:
                path: /admin/logout
                target: /admin/login
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
                always_use_default_target_path: true
                default_target_path: /admin/
        boom_area:
            pattern:    ^/
            anonymous: true
            remember_me:
              key:      "%secret%"
              lifetime: 3600
              path:     /login
            form_login:
                provider: boom_chain_provider
                csrf_provider: form.csrf_provider
            fos_facebook:
                check_path: /login_check_fb
                use_referer: true
                provider: boom_fos_facebook_provider
                success_handler: boom_front.facebook.auth_handler
                failure_handler: boom_front.facebook.auth_handler
            logout:
                path:   /logout
                handlers: ["fos_facebook.logout_handler"]
    access_control:
        - path: ^/_internal/secure
          roles: IS_AUTHENTICATED_ANONYMOUSLY
          ip: 127.0.0.1
        - path: ^/admin/login
          roles: IS_AUTHENTICATED_ANONYMOUSLY
        - path: ^/admin
          roles: ROLE_ADMIN
        - path: ^/login
          roles: IS_AUTHENTICATED_ANONYMOUSLY
        - path: ^/(boom|actividad|tu_sitio)
          roles: IS_AUTHENTICATED_FULLY
        - path: ^/
          roles: IS_AUTHENTICATED_ANONYMOUSLY