jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_SUPER_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin_login:
            pattern:  ^/admin/login$
            anonymous: ~
        boom_login:
            pattern:  ^/login$
            anonymous: ~
        admin_area:
            pattern:    ^/admin
            logout:
                path: /admin/logout
                target: /admin/login
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
                default_target_path: /admin
        boom_area:
            pattern:    ^/
            #logout:
            #    path: /logout
            #    target: /
            #form_login:
            #    check_path: /boomer/login_check
            #    login_path: /login
            #    default_target_path: /boomer
            anonymous: ~            
            fos_facebook:
                app_url: "http://apps.facebook.com/echo_mx/"
                server_url: "http://sb.here/"
                login_path: /login
                check_path: /login_check
                default_target_path: /
            logout:
                handlers: ["fos_facebook.logout_handler"]
    access_control:
        - path: ^/_internal/secure
          roles: IS_AUTHENTICATED_ANONYMOUSLY
          ip: 127.0.0.1
        - path: ^/admin/login
          roles: IS_AUTHENTICATED_ANONYMOUSLY
        - path: ^/login
          roles: IS_AUTHENTICATED_ANONYMOUSLY
        - path: ^/admin
          roles: ROLE_SUPER_ADMIN
        - path: ^/boomer
          roles: IS_AUTHENTICATED_FULLY
        - path: ^/
          roles: IS_AUTHENTICATED_ANONYMOUSLY