parameters:
  boom_library.user_image_upload_persist.listener.class: Boom\Bundle\LibraryBundle\Listener\UserImageUploadListener
  boom_library.image_upload_persist.listener.class: Boom\Bundle\LibraryBundle\Listener\ImageUploadListener
  boom_library.image.helper.class:            Boom\Bundle\LibraryBundle\Templating\Helper\ImageHelper
  boom_library.tags_selector.type.class:      Boom\Bundle\LibraryBundle\Form\Type\TagsSelectorType
  boom_library.ajax_image.type.class:         Boom\Bundle\LibraryBundle\Form\AjaxImageType
  boom_library.ajax_gallery.type.class:       Boom\Bundle\LibraryBundle\Form\AjaxGalleryType
  boom_library.ajax_image_upload.type.class:  Boom\Bundle\LibraryBundle\Form\AjaxImageUploadType
  boom_library.gallery_image.type.class:      Boom\Bundle\LibraryBundle\Form\GalleryImageType

services:
  boom_library.image_upload_persist.listener:
        class: %boom_library.image_upload_persist.listener.class%
        arguments:
            container:  "@service_container"
        tags:
            - { name: doctrine.event_listener, event: prePersist  }
            - { name: doctrine.event_listener, event: preUpdate   }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate  }
            - { name: doctrine.event_listener, event: postRemove  }
            - { name: doctrine.event_listener, event: preRemove   }
  boom_library.user_image_upload_persist.listener:
        class: %boom_library.user_image_upload_persist.listener.class%
        arguments:
            container:  "@service_container"
        tags:
            - { name: doctrine.event_listener, event: prePersist  }
            - { name: doctrine.event_listener, event: preUpdate   }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate  }
            - { name: doctrine.event_listener, event: postRemove  }
            - { name: doctrine.event_listener, event: preRemove   }
  boom_library.image.helper:
        class: %boom_library.image.helper.class%
        arguments:
            container:    "@service_container"
        tags:
            - { name: templating.helper, alias: boom_image }
  boom_library.tags_selector.type:
        class: %boom_library.tags_selector.type.class%
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: tags_selector }
  boom_library.ajax_image.type:
        class: %boom_library.ajax_image.type.class%
        arguments:
            om: "@doctrine.orm.entity_manager"
            image_helper: "@boom_library.image.helper"
        tags:
            - { name: form.type, alias: ajax_image }
  boom_library.ajax_gallery.type:
        class: %boom_library.ajax_gallery.type.class%
        arguments:
            om: "@doctrine.orm.entity_manager"
            image_helper: "@boom_library.image.helper"
        tags:
            - { name: form.type, alias: ajax_gallery }
  boom_library.ajax_image_upload.type:
        class: %boom_library.ajax_image_upload.type.class%
        arguments:
            om: "@doctrine.orm.entity_manager"
            image_helper: "@boom_library.image.helper"
        tags:
            - { name: form.type, alias: ajax_image_upload }
  boom_library.hidden_image.type:
        class: %boom_library.gallery_image.type.class%
        arguments:
            om: "@doctrine.orm.entity_manager"
            image_helper: "@boom_library.image.helper"
        tags:
            - { name: form.type, alias: gallery_image }

#  boom_library.boom_category_update.listener:
#        class: Boom\Bundle\LibraryBundle\Listener\BoomCategoryListener
#        tags:
#            - { name: doctrine.event_listener, event: preUpdate }
