parameters:
    boom_library.facebook.user.class: Boom\Bundle\LibraryBundle\Security\User\Provider\FacebookProvider
    boom_library.twitter.user.class: Boom\Bundle\LibraryBundle\Security\User\Provider\TwitterProvider
    boom_library.social.user.class: Boom\Bundle\LibraryBundle\Security\User\Provider\SocialProvider
    boom_library.bbcode.templating.helper.class: Boom\Bundle\LibraryBundle\Templating\Helper\BbcodeHelper
services:
    boom_library.facebook.user:
        class: %boom_library.facebook.user.class%
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            container: "@service_container"
    #boom_library.bbcode.templating.helper:
    #    class: %boom_library.bbcode.templating.helper.class%
    #    arguments:
    #        container: "@service_container"
    #    tags:
    #        - {name: templating.helper, alias: boom_bbcode }

    #boom_library.twitter.user:
    #    class: %boom_library.twitter.user.class%
    #    arguments:
    #        twitter_oauth: "@fos_twitter.api"
    #        userManager: "@fos_user.user_manager"
    #        validator: "@validator"
    #        session: "@session"
    #boom_library.social.user:
    #    class: %boom_library.social.user.class%
    #    arguments:
    #        facebook: "@fos_facebook.api"
    #        twitter_oauth: "@fos_twitter.api"
    #        userManager: "@fos_user.user_manager"
    #        validator: "@validator"
    #        session: "@session"