Boom\Bundle\LibraryBundle\Entity\Boom:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: slug
        - Callback:
            methods:   [validations]
    properties:
        slug:
          - Type:
              type: string
        title:
          - NotBlank: ~
          - NotNull: ~
          - Type:
              type: string
        elements:
          - Count:
                min: 7
                max: 7
          - Valid: ~
        date_created:
          - DateTime: ~
        date_published:
          - DateTime: ~
        nsfw:
          - Type:
              type: bool
        reply_enabled:
          - Type:
              type: bool
        status:
          - Type:
              type: integer
          - Range:
              min: 0
              max: 5
        image:
          - NotNull: ~
        user:
          - NotNull: ~
        category:
          - NotNull: ~
        featured:
          - DateTime: ~

Boom\Bundle\LibraryBundle\Entity\Image:
    properties:
      path:
        - NotBlank: ~
      file:
        - File:
                maxSize: 5120k
                mimeTypes: [image/png, image/jpeg, image/gif]

Boom\Bundle\LibraryBundle\Entity\ListGroup:
    properties:
      list_elements:
        - Valid: ~

Boom\Bundle\LibraryBundle\Entity\ListElement:
    properties:
      title:
        - NotBlank: ~
      url:
        - NotBlank: ~

Boom\Bundle\LibraryBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
      firstname:
        - MaxLength: 100
        - MinLength: 8
        - NotBlank: ~
      lastname:
        - MaxLength: 100
        - MinLength: 8
        - NotBlank: ~
      name:
        - MaxLength: 100
        - MinLength: 8
        - NotBlank: ~
      username:
        - MaxLength: 64
        - MinLength: 8
        - NotBlank: ~
      email:
        - NotBlank: ~
        - Email: ~
      collaborator:
        - Type:
            type: bool
            groups: [admin]
      profile_image:
        - File:
                maxSize: 5120k
                mimeTypes: [image/png, image/jpeg, image/gif]
