BoomFrontBundle_login_fb:
    pattern:  /login_fb

BoomFrontBundle_login_check_fb:
    pattern:   /login_check_fb

BoomFrontBundle_logout:
    pattern:  /logout

BoomFrontBundle_fos_user:
    resource: "@BoomFrontBundle/Resources/config/routing/fos_user.yml"

BoomFrontBundle_homepage:
    pattern:  /
    defaults: { _controller: BoomFrontBundle:Default:index }

BoomFrontBundle_list:
    resource: "@BoomFrontBundle/Resources/config/routing/list.yml"
    prefix:   /lista

BoomFrontBundle_user:
    resource: "@BoomFrontBundle/Resources/config/routing/user.yml"
    prefix:   /usuarios

BoomFrontBundle_boom:
    resource: "@BoomFrontBundle/Resources/config/routing/boom.yml"
    prefix:   /boom

BoomFrontBundle_activity:
    resource: "@BoomFrontBundle/Resources/config/routing/activity.yml"
    prefix:   /actividad

BoomFrontBundle_profile:
    resource: "@BoomFrontBundle/Resources/config/routing/profile.yml"
    prefix:   /tu_sitio


BoomFrontBundle_category_show:
    pattern:  /{slug}
    defaults: { _controller: "BoomFrontBundle:Default:category" }
    requirements:
        _method:  GET

BoomFrontBundle_boom_show:
    pattern:  /{category_slug}/{slug}
    defaults: { _controller: "BoomFrontBundle:Default:boom" }
    requirements:
        _method:  GET
