BoomFrontBundle_homepage:
    pattern:  /
    defaults: { _controller: BoomFrontBundle:Default:index }
    requirements:
        _method:  GET

BoomFrontBundle_security:
    resource: "@BoomFrontBundle/Resources/config/routing/security.yml"

BoomFrontBundle_user:
    resource: "@BoomFrontBundle/Resources/config/routing/user.yml"
    prefix:   /usuario

BoomFrontBundle_boom:
    resource: "@BoomFrontBundle/Resources/config/routing/boom.yml"
    prefix:   /boom

BoomFrontBundle_gallery:
    resource: "@BoomFrontBundle/Resources/config/routing/gallery.yml"
    prefix:   /gal

BoomFrontBundle_image:
    resource: "@BoomFrontBundle/Resources/config/routing/image.yml"
    prefix:   /img

BoomFrontBundle_activity:
    resource: "@BoomFrontBundle/Resources/config/routing/activity.yml"
    prefix:   /actividad

BoomFrontBundle_profile:
    resource: "@BoomFrontBundle/Resources/config/routing/profile.yml"
    prefix:   /tu_sitio

BoomFrontBundle_list:
    resource: "@BoomFrontBundle/Resources/config/routing/list.yml"
    requirements:
        _method:  GET

BoomFrontBundle_default:
    resource: "@BoomFrontBundle/Resources/config/routing/default.yml"