BoomFrontBundle_login_fb:
    pattern:  /login_fb
    defaults: { _controller: BoomFrontBundle:Profile:fbLogin }

BoomFrontBundle_login_check_fb:
    pattern:   /login_check_fb

BoomFrontBundle_logout:
    pattern:  /logout

BoomFrontBundle_homepage:
    pattern:  /
    defaults: { _controller: BoomFrontBundle:Default:index }

BoomFrontBundle_user:
    resource: "@BoomFrontBundle/Resources/config/routing/user.yml"
    prefix:   /usuario

BoomFrontBundle_boom:
    resource: "@BoomFrontBundle/Resources/config/routing/boom.yml"
    prefix:   /boom

BoomFrontBundle_gallery:
    resource: "@BoomFrontBundle/Resources/config/routing/gallery.yml"
    prefix:   /gal

BoomFrontBundle_image:
    resource: "@BoomFrontBundle/Resources/config/routing/image.yml"
    prefix:   /img

BoomFrontBundle_activity:
    resource: "@BoomFrontBundle/Resources/config/routing/activity.yml"
    prefix:   /actividad

BoomFrontBundle_profile:
    resource: "@BoomFrontBundle/Resources/config/routing/profile.yml"
    prefix:   /tu_sitio

BoomFrontBundle_list:
    resource: "@BoomFrontBundle/Resources/config/routing/list.yml"
    prefix:   /
    requirements:
        _method:  GET

BoomFrontBundle_boom_twit_count:
    pattern:  /tc/{category_slug}/{slug}
    defaults: { _controller: "BoomFrontBundle:Default:twitCount", _format: "json" }
    requirements:
        _method:  GET

BoomFrontBundle_category_show:
    pattern:  /{slug}
    defaults: { _controller: "BoomFrontBundle:Default:category" }
    requirements:
        _method:  GET

BoomFrontBundle_boom_show:
    pattern:  /{category_slug}/{slug}
    defaults: { _controller: "BoomFrontBundle:Default:boom" }
    requirements:
        _method:  GET
    options:
        expose: true
