BoomFrontBundle_login_fb:
    pattern:  /login_fb

BoomFrontBundle_logout:
    pattern:  /logout

BoomFrontBundle_login_check_fb:
    pattern:   /login_check_fb

BoomFrontBundle_homepage:
    pattern:  /
    defaults: { _controller: BoomFrontBundle:Default:index }

BoomFrontBundle_boom:
    resource: "@BoomFrontBundle/Resources/config/routing/boom.yml"
    prefix:   /boom

BoomFrontBundle_boom:
    resource: "@BoomFrontBundle/Resources/config/routing/category.yml"
    prefix:   /cat
