BoomFrontBundle_login:
    pattern:  /login
    defaults: { _controller: BoomFrontBundle:Auth:login }

BoomFrontBundle_login_check:
    pattern:   /login_check


BoomFrontBundle_homepage:
    pattern:  /
    defaults: { _controller: BoomFrontBundle:Default:index }
