parameters:
    boom_front.facebook.user.class: Boom\Bundle\FrontBundle\Security\User\Provider\FacebookProvider
    boom_front.main.helper.class: Boom\Bundle\FrontBundle\Templating\Helper\MainHelper
    boom_front.facebook.auth_handler.class: Boom\Bundle\FrontBundle\Security\Http\Authentication\FacebookAuthenticationHandler
    boom_front.gallery.decoda.filter.class: Boom\Bundle\FrontBundle\Decoda\Filter\BoomGalleryFilter

services:
    boom_front.facebook.user:
        class: %boom_front.facebook.user.class%
        arguments:
            facebook:     "@fos_facebook.api"
            userManager:  "@fos_user.user_manager"
            validator:    "@validator"
            container:    "@service_container"
            logging:      %fos_facebook.logging%
            culture:      %fos_facebook.culture%
            scope:        %fos_facebook.permissions%
    boom_front.main.helper:
        class: %boom_front.main.helper.class%
        arguments:
            container:    "@service_container"
        tags:
            - { name: templating.helper, alias: boom_front }
    boom_front.gallery.decoda.filter:
        class: %boom_front.gallery.decoda.filter.class%
        arguments:
            boom_front_helper:    "@boom_front.main.helper"

    boom_front.facebook.auth_handler:
        class: %boom_front.facebook.auth_handler.class%
        public: false
        arguments:
            securityContext: "@security.context"
            router: '@router'
        tags:
            - { name: 'monolog.logger', channel: 'security' }